version: '3.9'

services:
  app:
    build:
      context: .  # Adjusted to point to the root directory of your project
      dockerfile: .docker/Dockerfile  # Path to the Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_KEY=${APP_KEY}
      - NEXT_PUBLIC_APP_SECRET=${APP_SECRET}
      - NEXT_PUBLIC_API_ENDPOINT=${API_ENDPOINT}
    restart: "no"  # Prevents the container from restarting automatically
    deploy:
      restart_policy:
        condition: none  # Ensures that the container will not restart if it stops

networks:
  default:
    name: nextjs_network
