export const ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  VALIDATE_TOKEN: "/validate-token",
  LOGOUT: "/logout",
  UNAUTHORIZED: "/unauthorized",
  USERS_TOKEN: "/users/token",
  GET_DAILY_BALANCE: "/batoda-bank/daily-balance",
  GET_MONTHLY_REVENUE: "/batoda-bank/monthly-revenue",
  GET_YEARLY_REVENUE: "/batoda-bank/yearly-revenue",
  GET_BANK_RECORD_BY_DATE: (startDate: string, endDate: string) =>
    `/batoda-banks?start_date=${startDate}&end_date=${endDate}`,
  GET_AUTHENTICATED_USERS: "/authenticated-users",
  GET_USERS: "/users",
  APPROVE_USER: (id: number) => `/approve-user/user_id=${id}`,
  BLOCK_USER: (id: number) => `/users/${id}/block`,
  UNBLOCK_USER: (id: number) => `/users/${id}/unblock`,
  COUNT_ACTIVE_USERS: "/active-officers/count",
  COUNT_TOTAL_DRIVER_DISPATCHER: "/driver-dispatcher/count",
  GET_ALL_DRIVERS_DISPATCHERS: "/drivers-dispatchers",
  GET_OFFICERS: "/leadership-users",
  GET_ALL_USERS: "/get/users",
  GENERATE_QR: (id: number) => `/generate-qr/${id}`,
  GET_RESERVATION_HISTORY: "/reservations/receipt",
  GET_PASSENGERS: "/passengers",
  GET_TOTAL_CONTRIBUTION: "/total/contribution",
  GET_BATODA_LOGS: "/batodabank/logs",
  GET_DRIVER_MOST_SALES: "/drivers/most-sales",
  GET_REPORT: "/report/summary",
  UPDATE_USER: "/user/update",
  UPDATE_EMAIL_SEND_OTP: "/email-verification/send-otp",
  SEND_OTP_PASSWORD_RESET: "/password-reset/send-otp",
  VERIFY_OTP_FOR_PASSWORD_RESET: "/password-reset/verify",
  UPDATE_FARE: "/fare/update",
  GET_FARE: "/fare",
  UPDATE_PROFILE_PIC: "/users/upload-profile"
};
